# Generated by Django 5.0.3 on 2024-06-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_followings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
